Repository PLANlT/planit-server, pull requests merged in 2025-08, with the labels that each got.

#178 HOTFIX: auth/refresh 로깅 추가
  src/main/java/com/planit/planit/web/controller/AuthController.java
Labels: 🛠️ Fix, Patch

#179 [HOTFIX] Redis 저장 자료구조 변경
  src/main/java/com/planit/planit/auth/entity/BlacklistTokenRedisEntity.java
  src/main/java/com/planit/planit/auth/entity/MemberIdToRefreshTokenRedisEntity.java
  src/main/java/com/planit/planit/auth/entity/RefreshTokenToMemberIdRedisEntity.java
  src/main/java/com/planit/planit/auth/repository/MemberIdToRefreshTokenRedisRepository.java
  src/main/java/com/planit/planit/auth/repository/RefreshTokenToMemberIdRedisRepository.java
  src/main/java/com/planit/planit/auth/service/BlacklistTokenRedisService.java
  src/main/java/com/planit/planit/auth/service/BlacklistTokenRedisServiceImpl.java
  src/main/java/com/planit/planit/auth/service/RefreshTokenRedisService.java
  src/main/java/com/planit/planit/auth/service/RefreshTokenRedisServiceImpl.java
  src/main/java/com/planit/planit/config/RedisConfig.java
  src/main/resources/application-dev.yml
  src/test/java/com/planit/planit/auth/service/RefreshTokenRedisServiceTest.java
Labels: 🛠️ Fix, Patch

#184 [HOTFIX] 배포 시 시간대 UTC-> KST로 변경 및 문서 변경
  AUTO_LOGIN_FLOW.md
  Dockerfile
  readme.md
Labels: 📖 Docs, 🛠️ Fix, Patch

#187 [RELEASE] Deploy 1.0.0
  readme.md
  src/main/java/com/planit/planit/plan/Plan.java
Labels: ✈️ Deploy, Major
