Repository PLANlT/planit-server, pull requests merged in 2025-07, with the labels that each got.

#67 [PL-131] [test] 작업 기능 TaskService Test 작성
  src/main/java/com/planit/planit/task/association/CompletedTask.java
  src/main/java/com/planit/planit/task/service/TaskCommandService.java
  src/main/java/com/planit/planit/task/service/TaskCommandServiceImpl.java
  src/main/java/com/planit/planit/task/service/TaskQueryService.java
  src/main/java/com/planit/planit/task/service/TaskQueryServiceImpl.java
  src/main/java/com/planit/planit/web/dto/task/TaskResponseDTO.java
  src/main/java/com/planit/planit/web/dto/task/converter/TaskConverter.java
  src/test/java/com/planit/planit/member/service/MemberServiceImplTest.java
  src/test/java/com/planit/planit/task/service/TaskCommandServiceTest.java
  src/test/java/com/planit/planit/task/service/TaskQueryServiceTest.java
Labels: ✅ Test

#68 [PL-100] [feat] 작업 기능 1차 구현
  build.gradle
  gradlew
  src/main/java/com/planit/planit/common/api/plan/status/PlanErrorStatus.java
  src/main/java/com/planit/planit/common/api/task/status/TaskErrorStatus.java
  src/main/java/com/planit/planit/common/api/task/status/TaskSuccessStatus.java
  src/main/java/com/planit/planit/member/Member.java
  src/main/java/com/planit/planit/member/association/GuiltyFree.java
  src/main/java/com/planit/planit/plan/service/PlanCommandServiceImpl.java
  src/main/java/com/planit/planit/plan/service/PlanQueryServiceImpl.java
  src/main/java/com/planit/planit/task/Task.java
  src/main/java/com/planit/planit/task/association/CompletedTask.java
  src/main/java/com/planit/planit/task/service/TaskCommandService.java
  src/main/java/com/planit/planit/task/service/TaskCommandServiceImpl.java
  src/main/java/com/planit/planit/task/service/TaskQueryService.java
  src/main/java/com/planit/planit/task/service/TaskQueryServiceImpl.java
  src/main/java/com/planit/planit/web/controller/TaskController.java
  src/main/java/com/planit/planit/web/dto/plan/PlanResponseDTO.java
  src/main/java/com/planit/planit/web/dto/plan/converter/PlanConverter.java
  src/main/java/com/planit/planit/web/dto/task/TaskRequestDTO.java
  src/main/java/com/planit/planit/web/dto/task/TaskResponseDTO.java
  src/main/java/com/planit/planit/web/dto/task/converter/TaskConverter.java
  src/main/resources/application-prod.yml
  src/test/java/com/planit/planit/task/service/TaskCommandServiceTest.java
  src/test/java/com/planit/planit/task/service/TaskQueryServiceTest.java
Labels: 🌟 Feat

#72 [PL-136] test: MemberController 테스트코드 작성
  src/main/java/com/planit/planit/member/service/MemberService.java
  src/main/java/com/planit/planit/member/service/MemberServiceImpl.java
  src/main/java/com/planit/planit/web/controller/MemberController.java
  src/main/resources/application-oauth.yml
  src/test/java/com/planit/planit/member/service/MemberServiceImplTest.java
  src/test/java/com/planit/planit/web/controller/MemberControllerTest.java
Labels: ✏️ Task, ✅ Test

#79 [PL-143] Redis 설정 및 MemberService까지 연동
  .cursor/.cursorrules
  .cursor/rules/planit.mdc
  build.gradle
  src/main/java/com/planit/planit/PlanitApplication.java
  src/main/java/com/planit/planit/config/JpaAuditingConfig.java
  src/main/java/com/planit/planit/config/jwt/JwtProvider.java
  src/main/java/com/planit/planit/config/redis/RedisConfig.java
  src/main/java/com/planit/planit/member/service/MemberService.java
  src/main/java/com/planit/planit/member/service/MemberServiceImpl.java
  src/main/java/com/planit/planit/redis/entity/BlacklistTokenRedisEntity.java
  src/main/java/com/planit/planit/redis/entity/MemberIdToRefreshTokenRedisEntity.java
  src/main/java/com/planit/planit/redis/entity/RefreshTokenRedisEntity.java
  src/main/java/com/planit/planit/redis/entity/RefreshTokenToMemberIdRedisEntity.java
  src/main/java/com/planit/planit/redis/repository/BlacklistTokenRedisRepository.java
  src/main/java/com/planit/planit/redis/repository/MemberIdToRefreshTokenRedisRepository.java
  src/main/java/com/planit/planit/redis/repository/RefreshTokenRedisRepository.java
  src/main/java/com/planit/planit/redis/repository/RefreshTokenToMemberIdRedisRepository.java
  src/main/java/com/planit/planit/redis/service/BlacklistTokenRedisService.java
  src/main/java/com/planit/planit/redis/service/BlacklistTokenRedisServiceImpl.java
  src/main/java/com/planit/planit/redis/service/RefreshTokenRedisService.java
  src/main/java/com/planit/planit/redis/service/RefreshTokenRedisServiceImpl.java
  src/main/java/com/planit/planit/web/controller/MemberController.java
  src/main/java/com/planit/planit/web/dto/auth/login/OAuthLoginDTO.java
  src/main/resources/application.yml
  src/test/java/com/planit/planit/auth/service/AuthServiceImplTest.java
  src/test/java/com/planit/planit/config/redis/RefreshTokenRedisRepositoryTest.java
  src/test/java/com/planit/planit/member/service/MemberServiceImplTest.java
  src/test/java/com/planit/planit/redis/service/RefreshTokenRedisServiceTest.java
  src/test/java/com/planit/planit/web/controller/MemberControllerTest.java
Labels: ✏️ Task, ✅ Test, 🌟 Feat

#84 [PL-151] [task] 작업 루틴 다중 선택 가능하게 수정
  src/main/java/com/planit/planit/task/Task.java
  src/main/java/com/planit/planit/task/converter/RoutineConverter.java
  src/main/java/com/planit/planit/task/enums/RoutineDay.java
  src/main/java/com/planit/planit/task/service/TaskCommandServiceImpl.java
  src/main/java/com/planit/planit/web/dto/task/TaskRequestDTO.java
  src/main/java/com/planit/planit/web/dto/task/TaskResponseDTO.java
  src/main/java/com/planit/planit/web/dto/task/converter/TaskConverter.java
  src/test/java/com/planit/planit/task/repository/TaskRepositoryTest.java
  src/test/java/com/planit/planit/task/service/TaskCommandServiceTest.java
  src/test/java/com/planit/planit/task/service/TaskQueryServiceTest.java
Labels: ✏️ Task

#85 [PL-153][feat] 길티프리 기능 1차 구현
  src/main/java/com/planit/planit/common/api/member/status/MemberErrorStatus.java
  src/main/java/com/planit/planit/common/api/member/status/MemberSuccessStatus.java
  src/main/java/com/planit/planit/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/planit/planit/member/Member.java
  src/main/java/com/planit/planit/member/association/GuiltyFree.java
  src/main/java/com/planit/planit/member/enums/GuiltyFreeReason.java
  src/main/java/com/planit/planit/member/repository/GuiltyFreeRepository.java
  src/main/java/com/planit/planit/member/repository/MemberRepository.java
  src/main/java/com/planit/planit/member/repository/TermRepository.java
  src/main/java/com/planit/planit/member/service/GuiltyFreeService.java
  src/main/java/com/planit/planit/member/service/GuiltyFreeServiceImpl.java
  src/main/java/com/planit/planit/member/service/MemberService.java
  src/main/java/com/planit/planit/member/service/MemberServiceImpl.java
  src/main/java/com/planit/planit/plan/service/PlanCommandServiceImpl.java
  src/main/java/com/planit/planit/plan/service/PlanQueryServiceImpl.java
  src/main/java/com/planit/planit/task/service/TaskCommandServiceImpl.java
  src/main/java/com/planit/planit/task/service/TaskQueryServiceImpl.java
  src/main/java/com/planit/planit/web/controller/GuiltyFreeController.java
  src/main/java/com/planit/planit/web/dto/member/guiltyfree/GuiltyFreeResponseDTO.java
  src/test/java/com/planit/planit/config/oauth/JwtAuthenticationFilterTest.java
  src/test/java/com/planit/planit/jwt/JwtProviderTest.java
  src/test/java/com/planit/planit/member/MemberRepositoryTest.java
  src/test/java/com/planit/planit/member/service/MemberServiceImplTest.java
  src/test/java/com/planit/planit/plan/repository/PlanRepositoryTest.java
  src/test/java/com/planit/planit/plan/service/PlanCommandServiceTest.java
  src/test/java/com/planit/planit/plan/service/PlanQueryServiceTest.java
  src/test/java/com/planit/planit/task/repository/CompletedTaskRepositoryTest.java
  src/test/java/com/planit/planit/task/repository/TaskRepositoryTest.java
  src/test/java/com/planit/planit/task/service/TaskCommandServiceTest.java
  src/test/java/com/planit/planit/task/service/TaskQueryServiceTest.java
Labels: 🌟 Feat

#90 [RELEASE] Deploy 0.2.0
  .github/workflows/deploy.yml
  .github/workflows/prod-build-test.yml
  src/main/java/com/planit/planit/member/Member.java
Labels: ✈️ Deploy, Minor

#95 [PL-171] [feat] MemberController 로그인 기능 구현
  .cursor/rules/planit.mdc
  .github/workflows/prod-build-test.yml
  build.gradle
  src/main/java/com/planit/planit/common/api/general/status/ErrorStatus.java
  src/main/java/com/planit/planit/common/api/member/status/MemberErrorStatus.java
  src/main/java/com/planit/planit/common/api/member/status/MemberSuccessStatus.java
  src/main/java/com/planit/planit/common/api/token/TokenHandler.java
  src/main/java/com/planit/planit/common/api/token/status/TokenErrorStatus.java
  src/main/java/com/planit/planit/common/api/token/status/TokenSuccessStatus.java
  src/main/java/com/planit/planit/config/RestTemplateConfig.java
  src/main/java/com/planit/planit/config/SecurityConfig.java
  src/main/java/com/planit/planit/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/planit/planit/config/jwt/JwtProvider.java
  src/main/java/com/planit/planit/config/oauth/CustomOAuth2FailureHandler.java
  src/main/java/com/planit/planit/config/oauth/SocialTokenVerifier.java
  src/main/java/com/planit/planit/member/Member.java
  src/main/java/com/planit/planit/member/association/Term.java
  src/main/java/com/planit/planit/member/service/MemberService.java
  src/main/java/com/planit/planit/member/service/MemberServiceImpl.java
  src/main/java/com/planit/planit/redis/entity/RefreshTokenRedisEntity.java
  src/main/java/com/planit/planit/redis/repository/RefreshTokenRedisRepository.java
  src/main/java/com/planit/planit/web/controller/AuthController.java
  src/main/java/com/planit/planit/web/controller/MemberController.java
  src/main/java/com/planit/planit/web/dto/auth/login/OAuthLoginDTO.java
  src/main/java/com/planit/planit/web/dto/auth/login/TokenRefreshDTO.java
  src/main/java/com/planit/planit/web/dto/member/term/TermAgreementDTO.java
  src/main/resources/application-dev.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/test/java/com/planit/planit/auth/FakeCustomOAuth2User.java
  src/test/java/com/planit/planit/config/oauth/SocialTokenVerifierTest.java
  src/test/java/com/planit/planit/config/redis/RefreshTokenRedisRepositoryTest.java
  src/test/java/com/planit/planit/member/.gitkeep
  src/test/java/com/planit/planit/member/service/MemberServiceImplTest.java
  src/test/java/com/planit/planit/web/controller/MemberControllerTest.java
  src/test/java/com/planit/planit/web/controller/member/MemberControllerSignOutTest.java
  src/test/java/com/planit/planit/web/controller/member/MemberControllerTest.java
  src/test/java/com/planit/planit/web/controller/member/security/MemberControllerSignOutSecurityTest.java
Labels: ✏️ Task, 🌟 Feat

#108 [RELEASE] Deploy 0.4.0
  .github/workflows/deploy.yml
Labels: ✈️ Deploy, Minor

#109 [RELEASE] Deploy 0.5.0
  .github/workflows/deploy.yml
Labels: ✈️ Deploy, Minor

#111 [RELEASE] Deploy 0.3.0
  docker-compose.yml
Labels: ✈️ Deploy, Minor

#124 [RELEASE] Deploy 0.3.1
  src/main/java/com/planit/planit/common/api/member/status/MemberSuccessStatus.java
  src/main/java/com/planit/planit/config/SecurityConfig.java
  src/main/java/com/planit/planit/member/Member.java
  src/main/java/com/planit/planit/member/association/FcmToken.java
  src/main/java/com/planit/planit/member/association/Notification.java
  src/main/java/com/planit/planit/member/repository/FcmTokenRepository.java
  src/main/java/com/planit/planit/member/service/FcmTokenService.java
  src/main/java/com/planit/planit/member/service/FcmTokenServiceImpl.java
  src/main/java/com/planit/planit/member/service/MemberService.java
  src/main/java/com/planit/planit/member/service/MemberServiceImpl.java
  src/main/java/com/planit/planit/web/controller/MemberController.java
  src/main/java/com/planit/planit/web/dto/auth/OAuthLoginDTO.java
  src/main/java/com/planit/planit/web/dto/member/fcmtoken/FcmTokenDTO.java
  src/main/java/com/planit/planit/web/dto/member/term/TermAgreementDTO.java
  src/main/resources/static/TermOfInfo.html
  src/test/java/com/planit/planit/member/repository/FcmTokenRepositoryTest.java
  src/test/java/com/planit/planit/member/repository/NotificationRepositoryTest.java
  src/test/java/com/planit/planit/member/service/FcmTokenServiceImplTest.java
  src/test/java/com/planit/planit/web/controller/MemberControllerTest.java
  src/test/java/com/planit/planit/web/controller/auth/AuthControllerSecurityTest.java
  src/test/resources/application-oauth.yml
Labels: ✈️ Deploy, 🛠️ Fix, Major

#136 [PL-179] [task] 회원가입 약관동의 보안 로직 개선
  src/main/java/com/planit/planit/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/planit/planit/auth/jwt/JwtProvider.java
  src/main/java/com/planit/planit/auth/service/AuthServiceImpl.java
  src/main/java/com/planit/planit/common/api/ExceptionAdvice.java
  src/main/java/com/planit/planit/config/SecurityConfig.java
  src/main/java/com/planit/planit/member/association/SignedMember.java
  src/main/java/com/planit/planit/member/association/TermInfo.java
  src/main/java/com/planit/planit/member/service/MemberService.java
  src/main/java/com/planit/planit/member/service/MemberServiceImpl.java
  src/main/java/com/planit/planit/web/controller/MemberController.java
  src/main/java/com/planit/planit/web/dto/auth/OAuthLoginDTO.java
  src/main/java/com/planit/planit/web/dto/member/term/TermDTO.java
  src/main/resources/application-prod.yml
  src/main/resources/static/terms/TermOfInfo.html
  src/main/resources/static/terms/TermOfPrivacy.html
  src/main/resources/static/terms/TermOfUse.html
  src/main/resources/static/terms/ThirdPartyConsent.html
  src/test/java/com/planit/planit/auth/jwt/JwtProviderTest.java
  src/test/java/com/planit/planit/auth/service/AuthServiceImplTest.java
  src/test/java/com/planit/planit/member/service/TermServiceImplTest.java
  src/test/java/com/planit/planit/web/controller/auth/AuthControllerSecurityTest.java
  src/test/resources/application-oauth.yml
Labels: ✏️ Task, ♻️ Refactor

#137 [RELEASE] Deploy 0.4.0
  src/main/java/com/planit/planit/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/planit/planit/auth/jwt/JwtProvider.java
  src/main/java/com/planit/planit/auth/service/AuthServiceImpl.java
  src/main/java/com/planit/planit/common/api/ExceptionAdvice.java
  src/main/java/com/planit/planit/config/SecurityConfig.java
  src/main/java/com/planit/planit/member/association/SignedMember.java
  src/main/java/com/planit/planit/member/association/TermInfo.java
  src/main/java/com/planit/planit/member/service/MemberService.java
  src/main/java/com/planit/planit/member/service/MemberServiceImpl.java
  src/main/java/com/planit/planit/web/controller/MemberController.java
  src/main/java/com/planit/planit/web/dto/auth/OAuthLoginDTO.java
  src/main/java/com/planit/planit/web/dto/member/term/TermDTO.java
  src/main/resources/application-prod.yml
  src/main/resources/static/terms/TermOfInfo.html
  src/main/resources/static/terms/TermOfPrivacy.html
  src/main/resources/static/terms/TermOfUse.html
  src/main/resources/static/terms/ThirdPartyConsent.html
  src/test/java/com/planit/planit/auth/jwt/JwtProviderTest.java
  src/test/java/com/planit/planit/auth/service/AuthServiceImplTest.java
  src/test/java/com/planit/planit/member/service/TermServiceImplTest.java
  src/test/java/com/planit/planit/web/controller/auth/AuthControllerSecurityTest.java
  src/test/resources/application-oauth.yml
Labels: ✈️ Deploy, Minor

#145 [PL-183] fix: "TokenErrorStatus 수정"
  src/main/java/com/planit/planit/common/api/token/status/TokenErrorStatus.java
Labels: ✏️ Task, 🌱 Chore

#154 [RELEASE] Deploy 0.5.0
  src/main/java/com/planit/planit/common/api/ExceptionAdvice.java
  src/main/java/com/planit/planit/common/api/plan/status/PlanErrorStatus.java
  src/main/java/com/planit/planit/common/api/plan/status/PlanSuccessStatus.java
  src/main/java/com/planit/planit/common/api/token/status/TokenErrorStatus.java
  src/main/java/com/planit/planit/member/association/Term.java
  src/main/java/com/planit/planit/member/service/GuiltyFreeServiceImpl.java
  src/main/java/com/planit/planit/plan/Plan.java
  src/main/java/com/planit/planit/plan/service/PlanCommandService.java
  src/main/java/com/planit/planit/plan/service/PlanCommandServiceImpl.java
  src/main/java/com/planit/planit/plan/service/PlanQueryService.java
  src/main/java/com/planit/planit/plan/service/PlanQueryServiceImpl.java
  src/main/java/com/planit/planit/web/controller/PlanController.java
  src/main/java/com/planit/planit/web/dto/member/guiltyfree/GuiltyFreeResponseDTO.java
  src/main/java/com/planit/planit/web/dto/plan/PlanResponseDTO.java
  src/main/java/com/planit/planit/web/dto/plan/converter/PlanConverter.java
  src/test/java/com/planit/planit/plan/repository/PlanRepositoryTest.java
  src/test/java/com/planit/planit/plan/service/PlanCommandServiceTest.java
  src/test/java/com/planit/planit/plan/service/PlanQueryServiceTest.java
  src/test/java/com/planit/planit/task/repository/CompletedTaskRepositoryTest.java
  src/test/java/com/planit/planit/task/repository/TaskRepositoryTest.java
  src/test/java/com/planit/planit/task/service/TaskCommandServiceTest.java
  src/test/java/com/planit/planit/task/service/TaskQueryServiceTest.java
Labels: ✈️ Deploy, Minor

#156 [PL-186] [feat] Member 탈퇴 기능 구현
  build.gradle
  src/main/java/com/planit/planit/PlanitApplication.java
  src/main/java/com/planit/planit/common/api/member/status/MemberErrorStatus.java
  src/main/java/com/planit/planit/common/api/member/status/MemberSuccessStatus.java
  src/main/java/com/planit/planit/config/SchedulingConfig.java
  src/main/java/com/planit/planit/member/Member.java
  src/main/java/com/planit/planit/member/repository/MemberRepository.java
  src/main/java/com/planit/planit/member/service/MemberScheduler.java
  src/main/java/com/planit/planit/member/service/MemberService.java
  src/main/java/com/planit/planit/member/service/MemberServiceImpl.java
  src/main/java/com/planit/planit/web/controller/MemberController.java
  src/main/resources/application.yml
  src/test/java/com/planit/planit/member/service/MemberSchedulerTest.java
  src/test/java/com/planit/planit/member/service/MemberServiceImplTest.java
  src/test/java/com/planit/planit/web/controller/MemberControllerTest.java
Labels: 🌟 Feat

#160 [PL-188] [task] 오늘의 플랜 조회시 작업이 없는 플랜은 반환하지 않도록 수정
  src/main/java/com/planit/planit/plan/service/PlanQueryServiceImpl.java
  src/test/java/com/planit/planit/plan/service/PlanQueryServiceTest.java
Labels: ✏️ Task

#163 Hotfix: "탈퇴 회원 로그인시 신규 회원 저장 로직변경"
  src/main/java/com/planit/planit/member/Member.java
  src/main/java/com/planit/planit/member/repository/MemberRepository.java
  src/main/java/com/planit/planit/member/service/MemberServiceImpl.java
  src/test/java/com/planit/planit/member/repository/MemberRepositoryTest.java
  src/test/java/com/planit/planit/member/service/MemberServiceImplTest.java
Labels: ✈️ Deploy, Patch

#169 [Hotfix] "TermOfInfo 누락 문제 해결"
  src/main/resources/static/terms/TermOfInfo.html
Labels: Patch

#172 [HOTFIX] Deploy 0.6.4
  src/main/java/com/planit/planit/dream/Dream.java
  src/main/java/com/planit/planit/member/Member.java
  src/main/java/com/planit/planit/plan/service/PlanQueryServiceImpl.java
  src/main/java/com/planit/planit/task/Task.java
  src/main/java/com/planit/planit/web/dto/plan/converter/PlanConverter.java
Labels: 🛠️ Fix, Patch

#174 [HOTFIX] "TokenSuccessStatus 수정 및 리프레시 토큰 시간 조정"
  src/main/resources/application-prod.yml
Labels: 🛠️ Fix, Patch

#176 [HOTFIX] "auth/refresh 스웨거에서 안되는 문제 해결"
  src/main/java/com/planit/planit/web/controller/AuthController.java
Labels: 🛠️ Fix, Patch
